# Generated by Django 4.2.6 on 2023-10-19 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('character_class', models.CharField(max_length=50, verbose_name='Класс персонажа')),
                ('race', models.CharField(max_length=50, verbose_name='Раса')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень')),
                ('image', models.ImageField(blank=True, null=True, upload_to='character_images/', verbose_name='Изображение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
    ]
