# Generated by Django 4.2.6 on 2023-10-19 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('character_class', models.CharField(max_length=50, verbose_name='Класс персонажа')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень')),
                ('image', models.ImageField(blank=True, null=True, upload_to='character_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('characters', models.ManyToManyField(related_name='items', to='dnd_app.character', verbose_name='Персонажи')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип предмета')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Раса')),
                ('allowed_weight', models.PositiveIntegerField(verbose_name='Допустимый вес')),
            ],
            options={
                'verbose_name': 'Раса',
                'verbose_name_plural': 'Расы',
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dnd_app.item')),
                ('armor_type', models.CharField(choices=[('HEAVY', 'Тяжелый'), ('MEDIUM', 'Средний'), ('LIGHT', 'Легкий'), ('SHIELD', 'Щит')], default='LIGHT', max_length=50, verbose_name='Тип доспеха')),
                ('defense', models.PositiveIntegerField(blank=True, null=True, verbose_name='Защита')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес')),
            ],
            bases=('dnd_app.item',),
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dnd_app.item')),
                ('effect_type', models.CharField(choices=[('HEAL', 'Лечение'), ('BUFF', 'Усиление'), ('DEBUFF', 'Ослабление'), ('OTHER', 'Другое')], default='OTHER', max_length=50, verbose_name='Тип эффекта')),
                ('effect_strength', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сила эффекта')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Продолжительность действия')),
            ],
            options={
                'verbose_name_plural': 'Расходники',
            },
            bases=('dnd_app.item',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dnd_app.item')),
                ('weapon_type', models.CharField(choices=[('MELEE', 'Ближний бой'), ('RANGED', 'Дальний бой'), ('MAGIC', 'Магическое'), ('OTHER', 'Другое')], default='OTHER', max_length=50, verbose_name='Тип оружия')),
                ('damage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Урон')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес')),
            ],
            bases=('dnd_app.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.itemtype', verbose_name='Тип предмета'),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.race', verbose_name='Раса'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Ключ атрибута')),
                ('value', models.CharField(max_length=250, verbose_name='Значение атрибута')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_app.item')),
            ],
            options={
                'unique_together': {('item', 'key')},
            },
        ),
    ]
