# Generated by Django 4.2.2 on 2023-10-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0024_alter_task_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
            ],
        ),
    ]
