# Generated by Django 4.2.2 on 2023-10-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0016_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/images'),
        ),
    ]
