# Generated by Django 4.2.2 on 2023-10-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0017_documents_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название документа'),
        ),
    ]
