# Generated by Django 4.2.2 on 2023-10-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0021_taskhistory_remove_articlehistory_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='field_name',
            field=models.CharField(max_length=100, verbose_name='Название поля'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='new_value',
            field=models.TextField(blank=True, null=True, verbose_name='Новое значение поля'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='old_value',
            field=models.TextField(blank=True, null=True, verbose_name='Старое значение поля'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления'),
        ),
    ]
