# Generated by Django 4.2.2 on 2023-10-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0022_alter_taskhistory_field_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'ordering': ['-updated_at'], 'verbose_name': 'История изменений'},
        ),
    ]
