# Generated by Django 4.2.2 on 2023-10-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0025_adressbook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdressBook',
            new_name='AddressBook',
        ),
    ]
