# Generated by Django 4.2.2 on 2023-10-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0026_rename_adressbook_addressbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressbook',
            options={'verbose_name': 'Записная книжка'},
        ),
    ]
