# Generated by Django 4.2.1 on 2023-05-21 21:00

from django.db import migrations, models
import model.models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='calories',
            field=models.IntegerField(validators=[model.models.validate_positive_number]),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[model.models.validate_positive_number]),
        ),
    ]
