# Generated by Django 5.0 on 2023-12-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armor',
            options={'verbose_name': 'Броня'},
        ),
        migrations.AlterModelOptions(
            name='itemattribute',
            options={'verbose_name': 'Свойства предмета', 'verbose_name_plural': 'Свойства предметов'},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name_plural': 'Оружие'},
        ),
    ]
