# Generated by Django 5.0 on 2023-12-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_alter_armor_options_alter_itemattribute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=0, verbose_name='Харизма'),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(default=0, verbose_name='Телосложение'),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=0, verbose_name='Ловкость'),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=0, verbose_name='Интеллект'),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=0, verbose_name='Сила'),
        ),
        migrations.AddField(
            model_name='character',
            name='wisdom',
            field=models.IntegerField(default=0, verbose_name='Мудрость'),
        ),
    ]
