# Generated by Django 5.0 on 2023-12-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0003_character_charisma_character_constitution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor_class',
            field=models.IntegerField(default=10, verbose_name='Класс брони'),
        ),
        migrations.AddField(
            model_name='character',
            name='charisma_modifier',
            field=models.IntegerField(default=0, verbose_name='Модификатор Харизмы'),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution_modifier',
            field=models.IntegerField(default=0, verbose_name='Модификатор Телосложения'),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity_modifier',
            field=models.IntegerField(default=0, verbose_name='Модификатор Ловкости'),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence_modifier',
            field=models.IntegerField(default=0, verbose_name='Модификатор Интеллекта'),
        ),
        migrations.AddField(
            model_name='character',
            name='strength_modifier',
            field=models.IntegerField(default=0, verbose_name='Модификатор Силы'),
        ),
        migrations.AddField(
            model_name='character',
            name='wisdom_modifier',
            field=models.IntegerField(default=0, verbose_name='Модификатор Мудрости'),
        ),
    ]
