# Generated by Django 5.0 on 2023-12-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0004_character_armor_class_character_charisma_modifier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armor',
            options={'verbose_name': 'Броня', 'verbose_name_plural': 'Броня'},
        ),
    ]
